import * as React from 'react';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';

const ComboBox = () => {
  return (
    <Autocomplete
      disablePortal
      id="combo-box-demo"
      options={matchingSymptoms}
      sx={{ width: 300 }}
      renderInput={(params) => <TextField {...params} label="Symptom" />}
    />
  );
}

// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const matchingSymptoms = [
  {label :'back_pain'},
  { label: 'constipation'},
  { label: 'abdominal_pain'},
  { label: 'diarrhoea'},
  { label: 'mild_fever'},
  { label: 'yellow_urine'},
  { label: 'yellowing_of_eyes'},
  { label: 'acute_liver_failure'},
  { label: 'fluid_overload'},
  { label: 'swelling_of_stomach'},
  { label: 'swelled_lymph_nodes'},
  { label: 'malaise'},
  { label: 'blurred_and_distorted_vision'},
  { label: 'phlegm'},
  { label: 'throat_irritation'},
  { label: 'redness_of_eyes'},
  { label: 'sinus_pressure'},
  { label: 'runny_nose'},
  { label: 'congestion'},
  { label: 'chest_pain'},
  { label: 'weakness_in_limbs'},
  { label: 'fast_heart_rate'},
  { label: 'pain_during_bowel_movements'},
  { label: 'pain_in_anal_region'},
  { label: 'bloody_stool'},
  { label: 'irritation_in_anus'},
  { label: 'neck_pain'},
  { label: 'dizziness'},
  { label: 'cramps'},
  { label: 'bruising'},
  { label: 'obesity'},
  { label: 'swollen_legs'},
  { label: 'swollen_blood_vessels'},
  { label: 'puffy_face_and_eyes'},
  { label: 'enlarged_thyroid'},
  { label: 'brittle_nails'},
  { label: 'swollen_extremeties'},
  { label: 'excessive_hunger'},
  { label: 'extra_marital_contacts'},
  { label: 'drying_and_tingling_lips'},
  { label: 'slurred_speech'},
  { label: 'knee_pain'},
  { label: 'hip_joint_pain'},
  { label: 'muscle_weakness'},
  { label: 'stiff_neck'},
  { label: 'swelling_joints'},
  { label: 'movement_stiffness'},
  { label: 'spinning_movements'},
  { label: 'loss_of_balance'},
  { label: 'unsteadiness'},
  { label: 'weakness_of_one_body_side'},
  { label: 'loss_of_smell'},
  { label: 'bladder_discomfort'},
  { label: 'foul_smell_of urine'},
  { label: 'continuous_feel_of_urine'},
  { label: 'passage_of_gases'},
  { label: 'internal_itching'},
  { label: 'toxic_look_(typhos)'},
  { label: 'depression'},
  { label: 'irritability'},
  { label: 'muscle_pain'},
  { label: 'altered_sensorium'},
  { label:  'red_spots_over_body'},
  { label: 'belly_pain'},
  { label: 'abnormal_menstruation'},
  { label: 'dischromic _patches'},
  { label: 'watering_from_eyes'},
  { label: 'increased_appetite'},
  { label: 'polyuria'},
  { label: 'family_history'},
  { label: 'mucoid_sputum'},
  { label: 'rusty_sputum'},
  { label: 'lack_of_concentration'},
  { label: 'visual_disturbances'},
  { label: 'receiving_blood_transfusion'},
  { label: 'receiving_unsterile_injections'},
  { label:'coma'},
  { label:'stomach_bleeding'},
  { label:'distention_of_abdomen'},
  { label:'history_of_alcohol_consumption'},
  { label:'fluid_overload'},
  { label:'blood_in_sputum'},
  { label:'prominent_veins_on_calf'},
  { label:'palpitations'},
  { label:'painful_walking'},
  { label:'pus_filled_pimples'},
  { label:'blackheads'},
  { label:'scurring'},
  { label:'skin_peeling'},
  { label:'silver_like_dusting'},
  { label:'small_dents_in_nails'},
  { label:'inflammatory_nails'},
  { label:'blister'},
  { label:'red_sore_around_nose'},
  { label:'yellow_crust_ooze'},
];
export default ComboBox;

